/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.3.0
 *
 * Project: 'Boopit.Debug+STM32F746NGHx' 
 * Target:  'Debug+STM32F746NGHx' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
